// A 33³ LUT generated by the shared CPU transform keeps the GPU and .cube
// export on the same grid. Trilinear interpolation is an approximation between nodes.
import {applyTransform} from './color.js';
const states=new WeakMap();
function shader(gl,type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
function init(canvas){
 const surface=document.createElement('canvas');
 const gl=surface.getContext('webgl2',{alpha:true,premultipliedAlpha:false,preserveDrawingBuffer:true});
 if(!gl)return null;
 const program=gl.createProgram();
 gl.attachShader(program,shader(gl,gl.VERTEX_SHADER,`#version 300 es
 in vec2 position;out vec2 uv;void main(){uv=(position+1.0)*0.5;gl_Position=vec4(position,0,1);}`));
 gl.attachShader(program,shader(gl,gl.FRAGMENT_SHADER,`#version 300 es
 precision highp float;precision highp sampler3D;in vec2 uv;uniform sampler2D photo;uniform sampler3D lut;out vec4 color;void main(){vec4 p=texture(photo,vec2(uv.x,1.0-uv.y));color=vec4(texture(lut,p.rgb*(32.0/33.0)+vec3(0.5/33.0)).rgb,p.a);}`));
 gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))return null;gl.useProgram(program);
 const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);
 const location=gl.getAttribLocation(program,'position');gl.enableVertexAttribArray(location);gl.vertexAttribPointer(location,2,gl.FLOAT,false,0,0);
 const texture=gl.createTexture();gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,texture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.uniform1i(gl.getUniformLocation(program,'photo'),0);
 const lut=gl.createTexture();gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_3D,lut);for(const p of [gl.TEXTURE_MIN_FILTER,gl.TEXTURE_MAG_FILTER])gl.texParameteri(gl.TEXTURE_3D,p,gl.LINEAR);for(const p of [gl.TEXTURE_WRAP_S,gl.TEXTURE_WRAP_T,gl.TEXTURE_WRAP_R])gl.texParameteri(gl.TEXTURE_3D,p,gl.CLAMP_TO_EDGE);gl.uniform1i(gl.getUniformLocation(program,'lut'),1);
 const data=new Uint8ClampedArray(33**3*4);let i=0;for(let b=0;b<33;b++)for(let g=0;g<33;g++)for(let r=0;r<33;r++){data[i++]=r*255/32;data[i++]=g*255/32;data[i++]=b*255/32;data[i++]=255;}
 const state={gl,surface,texture,lut,grid:{data,width:33*33,height:33},photo:null,key:null};surface.addEventListener('webglcontextlost',e=>{e.preventDefault();states.set(canvas,null)});return state;
}
export function renderGPU(canvas,photo,settings,maxDimension=1400){try{
 if(!states.has(canvas))states.set(canvas,init(canvas));const s=states.get(canvas);if(!s||s.gl.isContextLost())return false;const {gl}=s;
 if(s.photo!==photo){const scale=Math.min(1,maxDimension/Math.max(photo.width,photo.height));s.surface.width=Math.round(photo.width*scale);s.surface.height=Math.round(photo.height*scale);const resized=document.createElement('canvas');resized.width=s.surface.width;resized.height=s.surface.height;resized.getContext('2d').drawImage(photo.image,0,0,resized.width,resized.height);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,s.texture);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,resized);s.photo=photo;}
 const key=JSON.stringify(settings);if(key!==s.key){const pixels=applyTransform(s.grid,settings);gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_3D,s.lut);gl.texImage3D(gl.TEXTURE_3D,0,gl.RGBA8,33,33,33,0,gl.RGBA,gl.UNSIGNED_BYTE,pixels.data);s.key=key;}
 gl.viewport(0,0,s.surface.width,s.surface.height);gl.drawArrays(gl.TRIANGLES,0,6);canvas.width=s.surface.width;canvas.height=s.surface.height;canvas.getContext('2d').drawImage(s.surface,0,0);return true;
 }catch(error){console.warn('GPU preview unavailable; using local CPU renderer.',error);states.set(canvas,null);return false;}}
